#!/bin/bash

# Script para migrar Icons de Material a Iconsax

# Archivos a procesar (excluyendo los ya migrados)
files=(
  "lib/features/pasajero/home_pasajero.dart"
  "lib/features/pasajero/presentation/pasajero_seguimiento_conductor_screen.dart"
  "lib/features/pasajero/widgets/route_info_card.dart"
  "lib/features/pasajero/widgets/service_type_selector.dart"
  "lib/features/pasajero/widgets/location_search_field.dart"
  "lib/features/pasajero/widgets/ride_confirmation_dialog.dart"
  "lib/features/conductor/home_conductor.dart"
  "lib/features/conductor/conductor_status_widget.dart"
  "lib/features/conductor/vehiculo_selector_page.dart"
  "lib/features/conductor/presentation/documentos_screen.dart"
  "lib/features/conductor/presentation/conductor_servicio_activo_screen.dart"
  "lib/features/conductor/widgets/turno_activo_card.dart"
  "lib/features/conductor/widgets/vehiculo_selection_sheet.dart"
  "lib/features/conductor/widgets/vehiculo_selection_dialog.dart"
  "lib/features/conductor/widgets/solicitud_servicio_card.dart"
  "lib/features/conductor/widgets/servicio_activo_info.dart"
  "lib/features/conductor/widgets/documentos_alert_dialog.dart"
  "lib/features/conductor/widgets/conductor_action_buttons.dart"
  "lib/features/rides/widgets/ride_request_bottom_sheet.dart"
  "lib/features/rides/widgets/calificacion_widgets.dart"
  "lib/features/rides/widgets/calificacion_dialog.dart"
  "lib/features/rides/widgets/requesting_service_modal.dart"
  "lib/features/rides/widgets/driver_offer_card.dart"
  "lib/features/rides/presentation/historial_calificaciones_screen.dart"
  "lib/features/rides/presentation/active_service_screen.dart"
  "lib/features/rides/presentation/ride_map_screen.dart"
  "lib/features/rides/presentation/pasajero_esperando_conductor_screen.dart"
  "lib/features/Profile/presentation/profile_screen.dart"
  "lib/features/Profile/presentation/profile_body_screen.dart"
  "lib/features/Profile/widget/menu_item_widget.dart"
  "lib/features/Profile/widget/cuenta_tab.dart"
  "lib/features/chat/presentation/chat_screen.dart"
  "lib/features/chat/presentation/chat_detail_screen.dart"
  "lib/features/chat/widgets/build_message_bubble_widget.dart"
  "lib/features/home/presentation/home_screen.dart"
  "lib/features/home/presentation/no_connection_screen.dart"
  "lib/features/home/presentation/custom_drawer.dart"
  "lib/features/auth/presentation/login_screen.dart"
  "lib/features/onboarding/presentation/onboarding_screen.dart"
  "lib/features/onboarding/widgets/onboarding_page_widget.dart"
  "lib/shared/app_feedback.dart"
  "lib/shared/optimized_image_widgets.dart"
)

echo "Iniciando migración de iconos a Iconsax..."
echo "Total de archivos a procesar: ${#files[@]}"

cd /Users/macbook/Desktop/TeleTaxi/intellitaxi

for file in "${files[@]}"; do
  if [ -f "$file" ]; then
    echo "Procesando: $file"
    
    # Agregar import de Iconsax si no existe
    if ! grep -q "iconsax_flutter" "$file"; then
      # Encontrar la última línea de import y agregar después
      sed -i '' '/^import.*flutter.*dart.*;$/a\
import '\''package:iconsax_flutter/iconsax_flutter.dart'\'';
' "$file"
    fi
    
    # Reemplazos de iconos más comunes
    sed -i '' 's/Icons\.person_outline/Iconsax.user_copy/g' "$file"
    sed -i '' 's/Icons\.person/Iconsax.user_copy/g' "$file"
    sed -i '' 's/Icons\.star_border/Iconsax.star_1_copy/g' "$file"
    sed -i '' 's/Icons\.star/Iconsax.star_1_copy/g' "$file"
    sed -i '' 's/Icons\.location_on_rounded/Iconsax.location_copy/g' "$file"
    sed -i '' 's/Icons\.location_on_outlined/Iconsax.location_copy/g' "$file"
    sed -i '' 's/Icons\.location_on/Iconsax.location_copy/g' "$file"
    sed -i '' 's/Icons\.location_off_rounded/Iconsax.location_slash_copy/g' "$file"
    sed -i '' 's/Icons\.phone_outlined/Iconsax.call_copy/g' "$file"
    sed -i '' 's/Icons\.phone/Iconsax.call_copy/g' "$file"
    sed -i '' 's/Icons\.directions_car_outlined/Iconsax.car_copy/g' "$file"
    sed -i '' 's/Icons\.directions_car/Iconsax.car_copy/g' "$file"
    sed -i '' 's/Icons\.local_taxi_rounded/Iconsax.car_copy/g' "$file"
    sed -i '' 's/Icons\.local_taxi/Iconsax.car_copy/g' "$file"
    sed -i '' 's/Icons\.shopping_bag_rounded/Iconsax.shopping_bag_copy/g' "$file"
    sed -i '' 's/Icons\.shopping_bag/Iconsax.shopping_bag_copy/g' "$file"
    sed -i '' 's/Icons\.check_circle_rounded/Iconsax.tick_circle_copy/g' "$file"
    sed -i '' 's/Icons\.check_circle/Iconsax.tick_circle_copy/g' "$file"
    sed -i '' 's/Icons\.check/Iconsax.tick_square_copy/g' "$file"
    sed -i '' 's/Icons\.error_outline/Iconsax.info_circle_copy/g' "$file"
    sed -i '' 's/Icons\.error/Iconsax.info_circle_copy/g' "$file"
    sed -i '' 's/Icons\.warning_amber/Iconsax.warning_2_copy/g' "$file"
    sed -i '' 's/Icons\.info_outline/Iconsax.info_circle_copy/g' "$file"
    sed -i '' 's/Icons\.info/Iconsax.info_circle_copy/g' "$file"
    sed -i '' 's/Icons\.access_time_outlined/Iconsax.clock_copy/g' "$file"
    sed -i '' 's/Icons\.access_time/Iconsax.clock_copy/g' "$file"
    sed -i '' 's/Icons\.calendar_today_outlined/Iconsax.calendar_copy/g' "$file"
    sed -i '' 's/Icons\.calendar_today/Iconsax.calendar_copy/g' "$file"
    sed -i '' 's/Icons\.my_location/Iconsax.gps_copy/g' "$file"
    sed -i '' 's/Icons\.send/Iconsax.send_2_copy/g' "$file"
    sed -i '' 's/Icons\.refresh_rounded/Iconsax.refresh_copy/g' "$file"
    sed -i '' 's/Icons\.refresh/Iconsax.refresh_copy/g' "$file"
    sed -i '' 's/Icons\.close/Iconsax.close_circle_copy/g' "$file"
    sed -i '' 's/Icons\.clear/Iconsax.close_circle_copy/g' "$file"
    sed -i '' 's/Icons\.cancel/Iconsax.close_circle_copy/g' "$file"
    sed -i '' 's/Icons\.arrow_forward_rounded/Iconsax.arrow_right_3_copy/g' "$file"
    sed -i '' 's/Icons\.arrow_forward_ios/Iconsax.arrow_right_3_copy/g' "$file"
    sed -i '' 's/Icons\.arrow_forward/Iconsax.arrow_right_3_copy/g' "$file"
    sed -i '' 's/Icons\.arrow_back/Iconsax.arrow_left_2_copy/g' "$file"
    sed -i '' 's/Icons\.chevron_left/Iconsax.arrow_left_2_copy/g' "$file"
    sed -i '' 's/Icons\.chevron_right/Iconsax.arrow_right_2_copy/g' "$file"
    sed -i '' 's/Icons\.keyboard_arrow_up/Iconsax.arrow_up_2_copy/g' "$file"
    sed -i '' 's/Icons\.keyboard_arrow_down/Iconsax.arrow_down_2_copy/g' "$file"
    sed -i '' 's/Icons\.visibility_off/Iconsax.eye_slash_copy/g' "$file"
    sed -i '' 's/Icons\.visibility/Iconsax.eye_copy/g' "$file"
    sed -i '' 's/Icons\.email/Iconsax.sms_copy/g' "$file"
    sed -i '' 's/Icons\.more_vert/Iconsax.more_copy/g' "$file"
    sed -i '' 's/Icons\.notifications_none/Iconsax.notification_copy/g' "$file"
    sed -i '' 's/Icons\.notifications/Iconsax.notification_copy/g' "$file"
    sed -i '' 's/Icons\.power_settings_new/Iconsax.power_copy/g' "$file"
    sed -i '' 's/Icons\.chat_bubble_outline/Iconsax.message_copy/g' "$file"
    sed -i '' 's/Icons\.chat/Iconsax.message_copy/g' "$file"
    sed -i '' 's/Icons\.attach_file/Iconsax.attach_circle_copy/g' "$file"
    sed -i '' 's/Icons\.search/Iconsax.search_normal_copy/g' "$file"
    sed -i '' 's/Icons\.map/Iconsax.map_copy/g' "$file"
    sed -i '' 's/Icons\.route/Iconsax.routing_2_copy/g' "$file"
    sed -i '' 's/Icons\.navigation/Iconsax.gps_copy/g' "$file"
    sed -i '' 's/Icons\.speed/Iconsax.speedometer_copy/g' "$file"
    sed -i '' 's/Icons\.straighten_outlined/Iconsax.ruler_copy/g' "$file"
    sed -i '' 's/Icons\.straighten/Iconsax.ruler_copy/g' "$file"
    sed -i '' 's/Icons\.wifi_off_rounded/Iconsax.wifi_square_copy/g' "$file"
    sed -i '' 's/Icons\.wifi_off/Iconsax.wifi_square_copy/g' "$file"
    sed -i '' 's/Icons\.airline_seat_recline_normal/Iconsax.profile_2user_copy/g' "$file"
    sed -i '' 's/Icons\.flag/Iconsax.flag_copy/g' "$file"
    sed -i '' 's/Icons\.done_all/Iconsax.tick_circle_copy/g' "$file"
    sed -i '' 's/Icons\.business/Iconsax.building_copy/g' "$file"
    sed -i '' 's/Icons\.verified_rounded/Iconsax.verify_copy/g' "$file"
    sed -i '' 's/Icons\.verified/Iconsax.verify_copy/g' "$file"
    sed -i '' 's/Icons\.shield_rounded/Iconsax.shield_tick_copy/g' "$file"
    sed -i '' 's/Icons\.shield/Iconsax.shield_tick_copy/g' "$file"
    sed -i '' 's/Icons\.explore_rounded/Iconsax.global_copy/g' "$file"
    sed -i '' 's/Icons\.explore/Iconsax.global_copy/g' "$file"
    sed -i '' 's/Icons\.waving_hand_rounded/Iconsax.emoji_happy_copy/g' "$file"
    sed -i '' 's/Icons\.waving_hand/Iconsax.emoji_happy_copy/g' "$file"
    sed -i '' 's/Icons\.hourglass_empty/Iconsax.timer_copy/g' "$file"
    sed -i '' 's/Icons\.inbox/Iconsax.archive_minus_copy/g' "$file"
    sed -i '' 's/Icons\.delete_sweep/Iconsax.trash_copy/g' "$file"
    sed -i '' 's/Icons\.delete/Iconsax.trash_copy/g' "$file"
    sed -i '' 's/Icons\.stop_circle/Iconsax.stop_circle_copy/g' "$file"
    sed -i '' 's/Icons\.center_focus_strong/Iconsax.frame_copy/g' "$file"
    sed -i '' 's/Icons\.local_offer/Iconsax.tag_copy/g' "$file"
    sed -i '' 's/Icons\.person_pin_circle/Iconsax.location_tick_copy/g' "$file"
    
    echo "✓ Completado: $file"
  else
    echo "⚠ No encontrado: $file"
  fi
done

echo ""
echo "✅ Migración completada!"
echo "Ejecutando dart format en los archivos modificados..."

flutter format lib/

echo "✅ Todo listo!"
