// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4VX2P7XJ8JtMpAjOIsToGYcLm88ueqTI',
    appId: '1:550853729681:web:e9fc754655ec81b4304e30',
    messagingSenderId: '550853729681',
    projectId: 'intellitaxi-8189e',
    authDomain: 'intellitaxi-8189e.firebaseapp.com',
    storageBucket: 'intellitaxi-8189e.firebasestorage.app',
    measurementId: 'G-9XF3H4SD6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlWYoh8hz-yC_DV-tMi_bwIhNxYUSPWHw',
    appId: '1:550853729681:android:38aca5e9076f6171304e30',
    messagingSenderId: '550853729681',
    projectId: 'intellitaxi-8189e',
    storageBucket: 'intellitaxi-8189e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWxa34wQZ1jWvo8tDb9tEoMDIjQ4dUsSA',
    appId: '1:550853729681:ios:b0c9e8f5b9d9786f304e30',
    messagingSenderId: '550853729681',
    projectId: 'intellitaxi-8189e',
    storageBucket: 'intellitaxi-8189e.firebasestorage.app',
    iosBundleId: 'com.virtualt.intellitaxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWxa34wQZ1jWvo8tDb9tEoMDIjQ4dUsSA',
    appId: '1:550853729681:ios:b0c9e8f5b9d9786f304e30',
    messagingSenderId: '550853729681',
    projectId: 'intellitaxi-8189e',
    storageBucket: 'intellitaxi-8189e.firebasestorage.app',
    iosBundleId: 'com.virtualt.intellitaxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4VX2P7XJ8JtMpAjOIsToGYcLm88ueqTI',
    appId: '1:550853729681:web:daf4e6c3e218f604304e30',
    messagingSenderId: '550853729681',
    projectId: 'intellitaxi-8189e',
    authDomain: 'intellitaxi-8189e.firebaseapp.com',
    storageBucket: 'intellitaxi-8189e.firebasestorage.app',
    measurementId: 'G-CPXQJW7SET',
  );
}
